USE Java_Projekt

CREATE TABLE Login_User
(
	IDUser INT PRIMARY KEY IDENTITY,
	Username NVARCHAR(50) NOT NULL,
	Password NVARCHAR(50) not null
)

CREATE TABLE Login_Administrator
(
	IDAdministrator INT PRIMARY KEY IDENTITY,
	Username NVARCHAR(50) NOT NULL,
	Password NVARCHAR(50) not null
)

CREATE TABLE Movie(
IDMovie INT PRIMARY KEY IDENTITY,
Title NVARCHAR(1000) NOT NULL,
Description NVARCHAR(4000) NOT NULL,
Producer NVARCHAR(2000) NOT NULL,
Actors NVARCHAR(2000) NOT NULL,
Duration NVARCHAR(100) NOT NULL,
Year NVARCHAR(100) NOT NULL
)

CREATE TABLE Favorite_Movie(
IDFavoriteMovie INT PRIMARY KEY IDENTITY,
Title NVARCHAR(1000) NOT NULL,
)



